### ISSUE TITLE
Error postman.py

### ISSUE THREAD

**Issue by wiltonjr** [rkistner/chinese-postman#12]
python postman.py --csv path.csv --gpx path.gpx --png path.png test_graph.csv
Traceback (most recent call last):
  File "postman.py", line 379, in <module>
    make_png(graph, args.png.name)
  File "postman.py", line 99, in make_png
    subprocess.call(['neato', '-n2', '-Tpng', '-o', path, dfile])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by peternowee** [comment]
I can reproduce this error by removing `/usr/bin/neato`, so I guess the `No such file or directory` error relates to `neato`, which is part of Graphviz. So, I think this particular error is caused by not having Graphviz installed. Additionally, you might need to install either pygraphviz or pydot (or maybe pydotplus) to bridge between networkx and Graphviz.
